# Generated by Django 5.1.7 on 2025-05-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_usuario_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='sinopse',
            field=models.CharField(default='teste', max_length=500),
            preserve_default=False,
        ),
    ]
