# Generated by Django 5.1.7 on 2025-05-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_film_sinopse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='ano',
            field=models.IntegerField(),
        ),
    ]
